spring.application.name=order-service
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=order_service;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Str0ng!Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver



spring.jpa.hibernate.ddl-auto=update
eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka



server.port=8082


management.health.circuitbreakers.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Resilience4j circuit breaker properties
resilience4j.circuitbreaker.instance.inventory.registerHealthIndicator=true
resilience4j.circuitbreaker.instance.inventory.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instance.inventory.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instance.inventory.slidingWindowSize=5
resilience4j.circuitbreaker.instance.inventory.failureRateThreshold=50
resilience4j.circuitbreaker.instance.inventory.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instance.inventory.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instance.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true



# Resilience4j timeout properties
resilience4j.timelimiter.instance.inventory.timeout-duration=3s


# Resilience4j retry properties
resilience4j.retry.instance.inventory.max-attempts=3
resilience4j.retry.instance.inventory.wait-duration=5s

management.tracing.sampling.probability=1.0
inventory.service.url=http://localhost:8084





# Kafka properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=notificationTopic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=event:com.programmingtechie.order_service.event.OrderPlacedEvent










