# Eureka
eureka.client.service-url.defaultZone=http://eureka:password@localhost:8761/eureka/

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=order_service;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Str0ng!Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Inventory Service
inventory.service.url=http://localhost:8084